---
apiVersion: v1
kind: Namespace
metadata:
  name: myns
  labels:
    dept: engineering
---
# write deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deploy
  namespace: myns
  labels:
    dept: engineering
    app: fortune 

spec:
  replicas: 2
  selector:
    matchLabels: 
      dept: engineering
      app: fortune-pod
  template:
  # pod yaml file
    metadata:
      name: fortune-pod
      labels:
        dept: engineering
        app: fortune-pod
    spec:
      containers:
      - name: fortune-container
        image: dockdockoriginal/fortune:v1
